### ISSUE TITLE
Sentry not sending events when using HTTPS

### ISSUE THREAD

**Issue by iBelieve** [getsentry/sentry-rust#62] opened 2018-07-18 20:37 UTC
I have an ARM Linux device that I'm using Sentry on. I've previously used the Python sentry client on it with no issues, and the Rust client also works correctly when testing from my local Arch Linux desktop. However, the Rust client isn't sending any events when running the device and using the HTTPS DSN. I've switched the DSN to HTTP and it works fine.

Here's my test case:

```
extern crate sentry;
extern crate env_logger;

fn main() {
    env_logger::init();

    let _guard = sentry::init("MY_DSN");
    sentry::capture_message("Hello World!", sentry::Level::Info);
    // when the guard goes out of scope here, the client will wait up to two
    // seconds to send remaining events to the service.
}
```

Here's the output I get with `RUST_LOG=trace`:

```
TRACE 2018-07-18T20:36:05Z: mio::poll: registering with poller
TRACE 2018-07-18T20:36:05Z: tokio_threadpool::builder: build; num-workers=1
DEBUG 2018-07-18T20:36:05Z: tokio_reactor::background: starting background reactor
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: consuming notification queue
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 649023 }
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop time - Instant { tv_sec: 3825, tv_nsec: 37692312 }
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 620355 }
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 21620413 }
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop time - Instant { tv_sec: 3825, tv_nsec: 60312426 }
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 742693 }
TRACE 2018-07-18T20:36:05Z: hyper::client::pool: park; waiting for idle connection: "https://sentry.io"
TRACE 2018-07-18T20:36:05Z: hyper::client::connect: Http::connect("https://sentry.io/api/236130/store/")
DEBUG 2018-07-18T20:36:05Z: hyper::client::dns: resolving host="sentry.io", port=443
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 5037174 }
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop time - Instant { tv_sec: 3825, tv_nsec: 68405706 }
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 730692 }
DEBUG 2018-07-18T20:36:05Z: hyper::client::connect: connecting to 35.188.42.15:443
TRACE 2018-07-18T20:36:05Z: mio::poll: registering with poller
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 31713762 }
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop time - Instant { tv_sec: 3825, tv_nsec: 101252507 }
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 661356 }
TRACE 2018-07-18T20:36:05Z: tokio_reactor: event Writable Token(0)
DEBUG 2018-07-18T20:36:05Z: tokio_reactor: loop process - 1 events, 0.000s
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 84162906 }
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop time - Instant { tv_sec: 3825, tv_nsec: 186465449 }
DEBUG 2018-07-18T20:36:05Z: tokio_core::reactor: loop process, Duration { secs: 0, nanos: 725692 }
TRACE 2018-07-18T20:36:05Z: tokio_reactor: event Readable | Writable Token(0)
DEBUG 2018-07-18T20:36:05Z: tokio_reactor: loop process - 1 events, 0.000s
TRACE 2018-07-18T20:36:05Z: mio::poll: deregistering handle with poller
DEBUG 2018-07-18T20:36:05Z: tokio_reactor: dropping I/O source: 0
```

**Comment by ryanmcgrath** [comment] 2018-07-21 19:19
Weird question, but is this with `actix-web`? I found that if I didn't explicitly throw `alpn` into the `features` section this'd happen.

I have no idea why, and am happy to be wrong and experiencing a coincidence.

**Comment by mitsuhiko** [comment] 2018-07-21 20:30
I can absolutely not reproduce this. We're using reqwest for this so I wonder if it makes more sense to file it against that library for a faster turnaround time.

**Comment by gabisurita** [comment] 2018-08-12 02:54
What target are you using? I had a similar problem with Musl builds and was able to solve with [this workround](https://github.com/emk/rust-musl-builder#making-openssl-work). Seems like a linking issue.

**Comment by mitsuhiko** [comment] 2018-08-30 16:52
Closing this as I cannot reproduce it.

**Closed by mitsuhiko** 2018-08-30 16:52 UTC
